#!/usr/bin/env bash

cd ..
PARENT_PATH=$(pwd)
EMBEDDING_MAIN_PATH=$PARENT_PATH/embedding
SENTENCE_PIECE_PATH=$PARENT_PATH/sentencepiece
GLOVE_PATH=$PARENT_PATH/glove
FASTTEXT_PATH=$PARENT_PATH/fastText
ELMO_PATH=$PARENT_PATH/bilm-tf
BERT_PATH=$PARENT_PATH/bert