FROM tensorflow/tensorflow:1.12.0-gpu-py3
MAINTAINER ratsgo <ratsgo@naver.com>

RUN apt-get update -y \
 && apt-get install -y wget language-pack-ko openjdk-8-jdk curl git-core

RUN locale-gen en_US.UTF-8 \
 && update-locale LANG=en_US.UTF-8

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-all-3.7.1.tar.gz \
 && mkdir /notebooks/protobuf-3.7.1 \
 && tar -zxf protobuf-all-3.7.1.tar.gz \
 && cd /notebooks/protobuf-3.7.1 \
 && ./configure && make && make install && ldconfig

RUN wget https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.sh \
 && mkdir /opt/cmake \
 && sh cmake-3.14.3-Linux-x86_64.sh --prefix=/opt/cmake --skip-license \
 && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

RUN pip install --upgrade pip
RUN pip install konlpy

WORKDIR /notebooks
RUN wget https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh \
 && bash mecab.sh
RUN rm -rf /notebooks/*

RUN git clone https://github.com/kakao/khaiii.git \
 && mkdir /notebooks/khaiii/build \
 && cd /notebooks/khaiii/build \
 && cmake .. && make all && make resource && make package_python \
 && cd /notebooks/khaiii/build/package_python \
 && rm setup.py \
 && wget https://gist.githubusercontent.com/ratsgo/ae99a267abc47506a767622aa682c65a/raw/f755ba622914cf2333eb4d60a3f7c8fef482a1d2/setup.py \
 && pip install  . \
 && PATH=$PATH:/notebooks/khaiii/build/lib

RUN pip install gensim soynlp bokeh networkx selenium lxml pyldavis

WORKDIR /notebooks
RUN git clone https://github.com/google/sentencepiece.git \
 && mkdir /notebooks/sentencepiece/build \
 && cd /notebooks/sentencepiece/build \
 && cmake .. \
 && make -j $(nproc) \
 && make install

WORKDIR /notebooks
RUN git clone http://github.com/stanfordnlp/glove \
 && cd /notebooks/glove && make

WORKDIR /notebooks
RUN git clone https://github.com/facebookresearch/fastText.git \
 && cd /notebooks/fastText && make

WORKDIR /notebooks
RUN git clone https://github.com/ratsgo/embedding.git \
 && cd /notebooks/embedding/models/swivel \
 && make -f fastprep.mk

WORKDIR /notebooks/embedding
CMD git pull origin master